on:
    push:

jobs:
    tests:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        name: Validate changes
        steps:
            - name: Checkout
              uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'

            - run: |
                  corepack enable
                  yarn --version

            - name: Run install
              run: |
                  yarn install

            - name: Lint
              run: |
                  yarn lint

            - name: Build
              run: |
                  yarn build

            - name: Install browsers
              run: |
                  yarn playwright install --with-deps chromium

            - name: Run Playwright tests
              run: |
                yarn playwright test

            - uses: actions/upload-artifact@v3
              if: always()
              with:
                name: playwright-report
                path: playwright-report/
                retention-days: 30